### ISSUE TITLE
Miss handling for crete-run crash within guest

### ISSUE THREAD

**Issue by likebreath** [SVL-PSU/crete-dev#25]
When crete-run is crashed within guest, vm/node and dispatch are not aware of it. vm-node and dispatch will do nothing but continue to wait for crete-run's finish signal (the "trace_ready" file .

**Comment by likebreath** [comment]
@moralismercatus, please let me know your thoughs about the fix on this issue. Thanks.

A quick fix came to my mind is adding a time-out to vm-node's FSM while waiting in the state of ["QemuFSM_::Testing()"](https://github.com/likebreath/crete-dev/blob/dev/lib/cluster/vm_node_fsm.cpp#L250). When the timer fires, kills the qemu instance and restart it.

**Comment by moralismercatus** [comment]
I agree with this solution. I had the same issue that I resolved the same way here: https://github.com/moralismercatus/crete-dev/blob/ovmf/lib/cluster/vm_node_fsm.cpp#L1226

**Comment by likebreath** [comment]
@moralismercatus Great. Thanks for the pointer.
