### ISSUE TITLE
klee-1.4 complains about randomize-fork argument

### ISSUE THREAD

**Issue by moralismercatus** [SVL-PSU/crete-dev#44]
https://github.com/SVL-PSU/crete-dev/blob/master/README.md#start-crete-dispatch-on-the-host-os

States to use randomize-fork=false as a CLI argument.

After upgrading to klee-1.4:

crete-klee-1.4.0: Unknown command line argument '-randomize-fork=false'.  Try: 'crete-klee-1.4.0 -help'
crete-klee-1.4.0: Did you mean '-max-forks=false'?

What is the appropriate flag to use?

Thanks,

**Comment by likebreath** [comment]
I believe this option is abandoned in klee-1.4.0. Just remove it from your script.

Yes, the documentation has been out-dated for a while. Please comment on issue #40 for additional issues on documentation.
